-- Storage Security Refactor: make message-attachments bucket private.
--
-- WHY: the bucket was public=true, meaning any file URL was permanently accessible
-- to anyone on the internet without authentication. Private bucket + signed URLs
-- limits access to thread participants, and URLs expire after 60 minutes.
--
-- STEPS:
--   1. Backfill file_path for old rows (file_path column added in batch4d_security).
--      Regex extracts the storage path from the legacy public file_url.
--      The one Cloudinary video row (file_url contains 'cloudinary') is intentionally
--      skipped (file_path stays NULL) and continues to be served from Cloudinary CDN.
--   2. Make the bucket private.
--   3. Drop the overly-broad storage.objects SELECT policy (any authenticated user).
--   4. Add a narrow SELECT policy: direct access only for the file's owner.
--      Recipients access files via signed URLs generated by /api/storage/signed-url
--      (which verifies thread participation server-side). Signed URLs bypass RLS.

-- ─── Step 1: Backfill file_path for existing Supabase Storage rows ────────────
UPDATE message_attachments
SET file_path = SUBSTRING(
  file_url
  FROM '/storage/v1/object/public/message-attachments/(.+)$'
)
WHERE file_path IS NULL
  AND file_url LIKE '%/storage/v1/object/public/message-attachments/%';
-- Rows with Cloudinary URLs do not match the LIKE pattern → file_path stays NULL (correct)

-- ─── Step 2: Make bucket private ─────────────────────────────────────────────
UPDATE storage.buckets
SET public = false
WHERE id = 'message-attachments';

-- ─── Step 3: Drop overly-broad SELECT policy ──────────────────────────────────
-- This policy allowed any authenticated user to access any file in the bucket.
-- With a private bucket it was already ineffective (public URLs bypass RLS),
-- but cleaning it up eliminates any future confusion.
DROP POLICY IF EXISTS "Users can read own message attachments" ON storage.objects;

-- ─── Step 4: Narrow SELECT policy: owner-only direct access ──────────────────
-- Legitimate cross-user access (recipients viewing sender's attachment) goes
-- through signed URLs which bypass storage RLS. Direct authenticated requests
-- are restricted to the uploader's own folder.
CREATE POLICY "Attachment owner direct access"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'message-attachments'
    AND (storage.foldername(name))[1] = (auth.uid())::text
  );
