export const countries: { value: string; sr: string; en: string }[] = [
  { value: 'Bosna i Hercegovina', sr: 'Bosna i Hercegovina', en: 'Bosnia and Herzegovina' },
  { value: 'Srbija', sr: 'Srbija', en: 'Serbia' },
  { value: 'Hrvatska', sr: 'Hrvatska', en: 'Croatia' },
  { value: 'Crna Gora', sr: 'Crna Gora', en: 'Montenegro' },
  { value: 'Slovenija', sr: 'Slovenija', en: 'Slovenia' },
  { value: 'Sjeverna Makedonija', sr: 'Sjeverna Makedonija', en: 'North Macedonia' },
  { value: 'Kosovo', sr: 'Kosovo', en: 'Kosovo' },
  { value: 'Albanija', sr: 'Albanija', en: 'Albania' },
  { value: 'Austrija', sr: 'Austrija', en: 'Austria' },
  { value: 'Njemačka', sr: 'Njemačka', en: 'Germany' },
  { value: 'Švicarska', sr: 'Švicarska', en: 'Switzerland' },
  { value: 'Luksemburg', sr: 'Luksemburg', en: 'Luxembourg' },
  { value: 'Švedska', sr: 'Švedska', en: 'Sweden' },
  { value: 'Norveška', sr: 'Norveška', en: 'Norway' },
  { value: 'Danska', sr: 'Danska', en: 'Denmark' },
  { value: 'Holandija', sr: 'Holandija', en: 'Netherlands' },
  { value: 'Belgija', sr: 'Belgija', en: 'Belgium' },
  { value: 'Francuska', sr: 'Francuska', en: 'France' },
  { value: 'Italija', sr: 'Italija', en: 'Italy' },
  { value: 'Španija', sr: 'Španija', en: 'Spain' },
  { value: 'Velika Britanija', sr: 'Velika Britanija', en: 'United Kingdom' },
  { value: 'SAD', sr: 'SAD', en: 'USA' },
  { value: 'Kanada', sr: 'Kanada', en: 'Canada' },
  { value: 'Australija', sr: 'Australija', en: 'Australia' },
  { value: 'Ostalo', sr: 'Ostalo', en: 'Other' },
];
