export const countries: { value: string; sr: string; en: string; de: string }[] = [
  { value: 'Bosna i Hercegovina', sr: 'Bosna i Hercegovina', en: 'Bosnia and Herzegovina', de: 'Bosnien und Herzegowina' },
  { value: 'Srbija', sr: 'Srbija', en: 'Serbia', de: 'Serbien' },
  { value: 'Hrvatska', sr: 'Hrvatska', en: 'Croatia', de: 'Kroatien' },
  { value: 'Crna Gora', sr: 'Crna Gora', en: 'Montenegro', de: 'Montenegro' },
  { value: 'Slovenija', sr: 'Slovenija', en: 'Slovenia', de: 'Slowenien' },
  { value: 'Sjeverna Makedonija', sr: 'Sjeverna Makedonija', en: 'North Macedonia', de: 'Nordmazedonien' },
  { value: 'Kosovo', sr: 'Kosovo', en: 'Kosovo', de: 'Kosovo' },
  { value: 'Albanija', sr: 'Albanija', en: 'Albania', de: 'Albanien' },
  { value: 'Austrija', sr: 'Austrija', en: 'Austria', de: 'Österreich' },
  { value: 'Njemačka', sr: 'Njemačka', en: 'Germany', de: 'Deutschland' },
  { value: 'Švicarska', sr: 'Švicarska', en: 'Switzerland', de: 'Schweiz' },
  { value: 'Luksemburg', sr: 'Luksemburg', en: 'Luxembourg', de: 'Luxemburg' },
  { value: 'Švedska', sr: 'Švedska', en: 'Sweden', de: 'Schweden' },
  { value: 'Norveška', sr: 'Norveška', en: 'Norway', de: 'Norwegen' },
  { value: 'Danska', sr: 'Danska', en: 'Denmark', de: 'Dänemark' },
  { value: 'Holandija', sr: 'Holandija', en: 'Netherlands', de: 'Niederlande' },
  { value: 'Belgija', sr: 'Belgija', en: 'Belgium', de: 'Belgien' },
  { value: 'Francuska', sr: 'Francuska', en: 'France', de: 'Frankreich' },
  { value: 'Italija', sr: 'Italija', en: 'Italy', de: 'Italien' },
  { value: 'Španija', sr: 'Španija', en: 'Spain', de: 'Spanien' },
  { value: 'Velika Britanija', sr: 'Velika Britanija', en: 'United Kingdom', de: 'Vereinigtes Königreich' },
  { value: 'SAD', sr: 'SAD', en: 'USA', de: 'USA' },
  { value: 'Kanada', sr: 'Kanada', en: 'Canada', de: 'Kanada' },
  { value: 'Australija', sr: 'Australija', en: 'Australia', de: 'Australien' },
  { value: 'Ostalo', sr: 'Ostalo', en: 'Other', de: 'Sonstiges' },
];
